export {default as PeoplePage} from './people-page'
export {default as Home} from './home'
export {default as StarShipPage} from './starship-page'
export {default as PlanetPage} from './planet-page'
export {default as SecretPage} from './secret-page'
export {default as Login} from './login'
